#!/bin/bash
#
# Make UI files editable that use PhoshLayerSurface

set -eu

function cleanup()
{
    [ -z "${TMP_DIR}" ] || rm -rf "${TMP_DIR}"
}

if [ -z "$1" ]; then
    echo "Usage: $0 <glade-ui-file>"
    exit 1
fi

trap cleanup EXIT

UI_FILE="$1"

TMP_DIR=$(mktemp -d)
TMP_UI_FILE="${TMP_DIR}/$(basename "${UI_FILE}")"

sed 's,parent="PhoshLayerSurface",parent="GtkWindow",' "${UI_FILE}" > "${TMP_UI_FILE}"

glade "${TMP_UI_FILE}"

sed 's,parent="GtkWindow",parent="PhoshLayerSurface",' "${TMP_UI_FILE}" > "${UI_FILE}"
